# SwiftLint configuration for VidPare
# https://github.com/realm/SwiftLint

# ─── Paths ─────────────────────────────────────────────────────────────────

included:
  - Sources
  - Tests

excluded:
  - .build
  - Packages
  - "**/.build"

# ─── Rules ─────────────────────────────────────────────────────────────────

# Rules disabled from the default set
disabled_rules:
  - trailing_whitespace          # handled by editor/formatter
  - todo                         # TODOs are acceptable during active development

# Rules enabled beyond the default set (opt-in)
opt_in_rules:
  - empty_count                  # prefer isEmpty over .count == 0
  - empty_string                 # prefer isEmpty over == ""
  - sorted_imports               # keep import statements sorted
  - operator_usage_whitespace    # consistent spacing around operators
  - closure_spacing              # spaces inside closure braces
  - collection_alignment         # align collection literal elements
  - contains_over_first_not_nil  # prefer contains over first != nil
  - discouraged_optional_boolean # avoid Bool? when Bool suffices
  - explicit_init                # .init() preferred over Type()
  - fallthrough                  # explicit fallthrough is intentional
  - first_where                  # prefer first(where:) over filter().first
  - legacy_random                # use Swift random APIs, not arc4random
  - literal_expression_end_indentation
  - multiline_arguments          # consistent multiline argument formatting
  - multiline_function_chains
  - multiline_parameters
  - redundant_nil_coalescing     # remove ?? nil
  - unavailable_function         # mark unavailable code clearly

# ─── Thresholds ────────────────────────────────────────────────────────────

line_length:
  warning: 200
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 350
  error: 500

file_length:
  warning: 500
  error: 1000
  # No option exists to ignore comments here

function_body_length:
  warning: 80
  error: 150

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

# ─── Custom rules ──────────────────────────────────────────────────────────

custom_rules:
  no_print_in_sources:
    name: "No print() in Sources"
    message: "Use os_log or Logger instead of print() in production code."
    regex: '^\s*print\('
    included: "Sources/.*\\.swift"
    severity: warning
